/**
 * Controlled vocabularies and synonym maps for deterministic PI/NOFO normalization.
 * Edit here to tune concepts without code changes elsewhere.
 */

/** Canonical science / biology theme tags */
export const SCIENCE_CANONICAL = [
  "tumor_immunology",
  "cancer_immunotherapy",
  "immunology",
  "autoimmunity",
  "transplant_immunology",
  "microbiome_immunity",
  "vaccine_immunology",
  "innate_immunity",
  "adaptive_immunity",
  "t_cell_biology",
  "myeloid_biology",
  "antigen_presentation",
  "checkpoint_immunotherapy",
  "computational_biology",
  "biomedical_imaging",
  "basic_research",
  "translational_research",
  "clinical_research",
  "population_health",
  "health_services_research",
  "neuroscience",
  "cardiovascular_biology",
  "metabolic_disease",
  "genetics_genomics",
  "environmental_health",
  "mental_health_research",
  "aging_research",
  "musculoskeletal_research",
  "pediatric_research",
  "career_development",
] as const;

/** Canonical disease / population tags */
export const DISEASE_CANONICAL = [
  "solid_tumor",
  "hematologic_malignancy",
  "melanoma",
  "lung_cancer",
  "breast_cancer",
  "gi_cancer",
  "brain_tumor",
  "inflammatory_disease",
  "infectious_disease",
  "rare_disease",
  "pulmonary_fibrosis",
  "lung_disease",
  "type_1_diabetes",
  "diabetes",
  "cardiovascular_disease",
  "kidney_disease",
  "liver_disease",
  "stroke",
  "neurodegenerative_disease",
  "obesity",
  "hypertension",
  "asthma",
  "hiv_aids",
  "hepatitis",
] as const;

/** Methods / platforms */
export const METHOD_CANONICAL = [
  "single_cell_genomics",
  "spatial_omics",
  "flow_cytometry",
  "mass_cytometry",
  "crispr_functional_genomics",
  "mouse_models",
  "human_samples",
  "clinical_trials_methods",
  "imaging",
  "proteomics",
  "bioinformatics",
  "machine_learning",
  "transcriptomics",
  "epidemiology",
  "biostatistics",
  "cohort_studies",
  "registry_research",
  "implementation_science",
  "consortium_coordination",
  "qualitative_research",
  "observational_studies",
  "health_outcomes_research",
] as const;

/** Translational / asset tags */
export const TRANSLATIONAL_CANONICAL = [
  "biospecimens",
  "biobank_access",
  "clinical_cohorts",
  "patient_derived_models",
  "glp_gmp_transition",
  "early_phase_trial",
] as const;

export type ScienceTag = (typeof SCIENCE_CANONICAL)[number];
export type DiseaseTag = (typeof DISEASE_CANONICAL)[number];
export type MethodTag = (typeof METHOD_CANONICAL)[number];
export type TranslationalTag = (typeof TRANSLATIONAL_CANONICAL)[number];

/** phrase / token → canonical science tag */
export const SCIENCE_SYNONYMS: Record<string, ScienceTag> = {
  "cancer immunology": "tumor_immunology",
  "tumor immunology": "tumor_immunology",
  "tumor microenvironment": "tumor_immunology",
  "tme": "tumor_immunology",
  "cancer immunotherapy": "cancer_immunotherapy",
  "immuno-oncology": "cancer_immunotherapy",
  immunotherapy: "cancer_immunotherapy",
  immunology: "immunology",
  autoimmune: "autoimmunity",
  autoimmunity: "autoimmunity",
  transplant: "transplant_immunology",
  microbiome: "microbiome_immunity",
  vaccine: "vaccine_immunology",
  "innate immunity": "innate_immunity",
  "adaptive immunity": "adaptive_immunity",
  "t cell": "t_cell_biology",
  "t-cell": "t_cell_biology",
  "b cell": "adaptive_immunity",
  myeloid: "myeloid_biology",
  "antigen presentation": "antigen_presentation",
  "checkpoint": "checkpoint_immunotherapy",
  "pd-1": "checkpoint_immunotherapy",
  "pd-l1": "checkpoint_immunotherapy",
  ctla: "checkpoint_immunotherapy",
  "computational biology": "computational_biology",
  bioinformatics: "computational_biology",
  "systems biology": "computational_biology",
  "biomedical imaging": "biomedical_imaging",
  radiology: "biomedical_imaging",
  "medical imaging": "biomedical_imaging",
  "basic research": "basic_research",
  "fundamental research": "basic_research",
  mechanistic: "basic_research",
  translational: "translational_research",
  "bench to bedside": "translational_research",
  "clinical research": "clinical_research",
  interventional: "clinical_research",
  "population health": "population_health",
  epidemiology: "population_health",
  epidemiologic: "population_health",
  "health services research": "health_services_research",
  "implementation science": "health_services_research",
  neuroscience: "neuroscience",
  neurology: "neuroscience",
  neurobiology: "neuroscience",
  neurological: "neuroscience",
  cardiovascular: "cardiovascular_biology",
  cardiac: "cardiovascular_biology",
  cardiometabolic: "metabolic_disease",
  metabolic: "metabolic_disease",
  endocrine: "metabolic_disease",
  genomics: "genetics_genomics",
  genetics: "genetics_genomics",
  genome: "genetics_genomics",
  "environmental health": "environmental_health",
  toxicology: "environmental_health",
  psychiatry: "mental_health_research",
  "mental health": "mental_health_research",
  behavioral: "mental_health_research",
  aging: "aging_research",
  geriatric: "aging_research",
  senescence: "aging_research",
  arthritis: "musculoskeletal_research",
  musculoskeletal: "musculoskeletal_research",
  orthopedic: "musculoskeletal_research",
  pediatric: "pediatric_research",
  pediatrics: "pediatric_research",
  "child health": "pediatric_research",
  "career development": "career_development",
  "k award": "career_development",
  "k99": "career_development",
  "k08": "career_development",
};

export const DISEASE_SYNONYMS: Record<string, DiseaseTag> = {
  cancer: "solid_tumor",
  oncology: "solid_tumor",
  tumor: "solid_tumor",
  carcinoma: "solid_tumor",
  melanoma: "melanoma",
  "lung cancer": "lung_cancer",
  nsclc: "lung_cancer",
  "breast cancer": "breast_cancer",
  "colorectal": "gi_cancer",
  "gi cancer": "gi_cancer",
  "hematologic": "hematologic_malignancy",
  leukemia: "hematologic_malignancy",
  lymphoma: "hematologic_malignancy",
  "brain tumor": "brain_tumor",
  glioma: "brain_tumor",
  inflammation: "inflammatory_disease",
  "inflammatory bowel": "inflammatory_disease",
  infection: "infectious_disease",
  pathogen: "infectious_disease",
  "rare disease": "rare_disease",
  "pulmonary fibrosis": "pulmonary_fibrosis",
  "lung fibrosis": "pulmonary_fibrosis",
  "idiopathic pulmonary fibrosis": "pulmonary_fibrosis",
  ipf: "pulmonary_fibrosis",
  fibrosis: "pulmonary_fibrosis",
  "lung disease": "lung_disease",
  "respiratory disease": "lung_disease",
  copd: "lung_disease",
  diabetes: "diabetes",
  "type 1 diabetes": "type_1_diabetes",
  "type i diabetes": "type_1_diabetes",
  t1d: "type_1_diabetes",
  "cardiovascular disease": "cardiovascular_disease",
  cardiovascular: "cardiovascular_disease",
  atherosclerosis: "cardiovascular_disease",
  cardiomyopathy: "cardiovascular_disease",
  "heart disease": "cardiovascular_disease",
  "heart failure": "cardiovascular_disease",
  renal: "kidney_disease",
  kidney: "kidney_disease",
  nephrology: "kidney_disease",
  hepatic: "liver_disease",
  liver: "liver_disease",
  stroke: "stroke",
  alzheimer: "neurodegenerative_disease",
  parkinson: "neurodegenerative_disease",
  dementia: "neurodegenerative_disease",
  neurodegenerative: "neurodegenerative_disease",
  obesity: "obesity",
  hypertensive: "hypertension",
  hypertension: "hypertension",
  asthma: "asthma",
  hiv: "hiv_aids",
  aids: "hiv_aids",
  hepatitis: "hepatitis",
};

export const METHOD_SYNONYMS: Record<string, MethodTag> = {
  "single-cell": "single_cell_genomics",
  "single cell": "single_cell_genomics",
  scrna: "single_cell_genomics",
  "scrna-seq": "single_cell_genomics",
  "single-cell rna": "single_cell_genomics",
  "single-cell sequencing": "single_cell_genomics",
  "single-cell rna-seq": "single_cell_genomics",
  "spatial transcript": "spatial_omics",
  "spatial omics": "spatial_omics",
  "flow cytometry": "flow_cytometry",
  cytof: "mass_cytometry",
  "mass cytometry": "mass_cytometry",
  crispr: "crispr_functional_genomics",
  "mouse model": "mouse_models",
  murine: "mouse_models",
  "human samples": "human_samples",
  "patient samples": "human_samples",
  "clinical specimens": "human_samples",
  biospecimen: "human_samples",
  biospecimens: "human_samples",
  "clinical trial": "clinical_trials_methods",
  imaging: "imaging",
  proteomic: "proteomics",
  proteomics: "proteomics",
  bioinformatic: "bioinformatics",
  bioinformatics: "bioinformatics",
  "machine learning": "machine_learning",
  "deep learning": "machine_learning",
  "artificial intelligence": "machine_learning",
  ai: "machine_learning",
  transcriptomics: "transcriptomics",
  "gene expression profiling": "transcriptomics",
  "bulk rna": "transcriptomics",
  "rna-seq": "transcriptomics",
  "rna sequencing": "transcriptomics",
  epidemiology: "epidemiology",
  epidemiologic: "epidemiology",
  biostatistics: "biostatistics",
  biostatistical: "biostatistics",
  "cohort study": "cohort_studies",
  "cohort studies": "cohort_studies",
  longitudinal: "cohort_studies",
  registry: "registry_research",
  "data registry": "registry_research",
  repository: "registry_research",
  "implementation science": "implementation_science",
  "multi-site": "consortium_coordination",
  "multisite": "consortium_coordination",
  multicenter: "consortium_coordination",
  "multi center": "consortium_coordination",
  consortium: "consortium_coordination",
  qualitative: "qualitative_research",
  observational: "observational_studies",
  "health outcomes": "health_outcomes_research",
  "electronic health record": "health_outcomes_research",
  ehr: "health_outcomes_research",
};

export const TRANSLATIONAL_SYNONYMS: Record<string, TranslationalTag> = {
  "human samples": "biospecimens",
  "patient samples": "biospecimens",
  "clinical specimens": "biospecimens",
  biobank: "biobank_access",
  biobanks: "biobank_access",
  "tissue bank": "biobank_access",
  "clinical cohort": "clinical_cohorts",
  "patient cohort": "clinical_cohorts",
  "patient-derived": "patient_derived_models",
  pdx: "patient_derived_models",
  organoid: "patient_derived_models",
  "phase i": "early_phase_trial",
  "phase 1": "early_phase_trial",
  "early phase": "early_phase_trial",
};
